# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
defaults: &defaults
  working_directory: /build
  docker:
    - image: pinster/node:6

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name:  Build
          command:  npm install --production
      - persist_to_workspace:
          root: /build
          paths:
            - src

  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Run tests
          command: npm test

  deploy-dev:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /build
      - run:
          name: Build React
          command: npm run build
      - run:
          name: Install serverless
          command: npm install -g serverless
      - run:
          name: Deploy
          command: serverless deploy --stage dev

  deploy-prod:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /build
      - run:
          name: Build React
          command: npm run build
      - run:
          name: Install serverless
          command: npm install -g serverless
      - run:
          name: Deploy
          command: serverless deploy --stage prod

workflows:
  version: 2
  commit:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-dev:
          requires:
            - test
          filters:
            branches:
              only:
                - develop

      - deploy-prod:
          requires:
            - test
          filters:
            branches:
              only:
                - master
