# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
defaults: &defaults
  working_directory: /build
  docker:
    - image: pinster/node:6

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name:  Build
          command:  npm install --production
      - persist_to_workspace:
          root: /build
          paths:
            - /

  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Run tests
          command: npm test

  deploy-dev-serverless:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /build
      - run:
          name: Build React
          command: npm run build
      - run:
          name: Install serverless
          command: npm install -g serverless
      - run:
          name: Deploy serverless
          command: serverless deploy --stage dev

  deploy-dev-react:
    <<: *defaults
    docker:
      - image: pinster/awseb
    steps:
      - checkout
      - attach_workspace:
          at: /build
      - run:
          name: Deploy React
          command: aws s3 cp build s3://api-dev.pinster.io/

  deploy-prod-serverless:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /build
      - run:
          name: Build React
          command: npm run build
      - run:
          name: Install serverless
          command: npm install -g serverless
      - run:
          name: Deploy
          command: serverless deploy --stage prod
  
  deploy-prod-react:
    <<: *defaults
    docker:
      - image: pinster/awseb
    steps:
      - checkout
      - attach_workspace:
          at: /build
      - run:
          name: Deploy React
          command: aws s3 cp build s3://api-prod.pinster.io/

workflows:
  version: 2
  commit:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-dev-serverless:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
      - deploy-dev-react:
          requires:
            - test
            - deploy-dev-serverless
          filters:
            branches:
              only:
                - develop
      - deploy-prod-serverless:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy-prod-react:
          requires:
            - test
            - deploy-prod-serverless
          filters:
            branches:
              only:
                - master
